part of space_penguin;

Map<int, String> KEY_MAP = {
  KeyCode.A: "a",
  KeyCode.B: "b",
  KeyCode.C: "c",
  KeyCode.D: "d",
  KeyCode.E: "e",
  KeyCode.F: "f",
  KeyCode.G: "g",
  KeyCode.H: "h",
  KeyCode.I: "i",
  KeyCode.J: "j",
  KeyCode.K: "k",
  KeyCode.L: "l",
  KeyCode.M: "m",
  KeyCode.N: "n",
  KeyCode.O: "o",
  KeyCode.P: "p",
  KeyCode.Q: "q",
  KeyCode.R: "r",
  KeyCode.S: "s",
  KeyCode.T: "t",
  KeyCode.U: "u",
  KeyCode.V: "v",
  KeyCode.W: "w",
  KeyCode.X: "x",
  KeyCode.Y: "y",
  KeyCode.Z: "z",
  KeyCode.ZERO: "0",
  KeyCode.ONE: "1",
  KeyCode.TWO: "2",
  KeyCode.THREE: "3",
  KeyCode.FOUR: "4",
  KeyCode.FIVE: "5",
  KeyCode.SIX: "6",
  KeyCode.SEVEN: "7",
  KeyCode.EIGHT: "8",
  KeyCode.NINE: "9",
  KeyCode.SPACE: " ",
  KeyCode.COMMA : ",",
  KeyCode.PERIOD : ".",
  KeyCode.SEMICOLON: ";",
  KeyCode.SINGLE_QUOTE : "'",
  KeyCode.OPEN_SQUARE_BRACKET : "[",
  KeyCode.CLOSE_SQUARE_BRACKET : "]",
  KeyCode.BACKSLASH : "/",
  KeyCode.SLASH : "\\",
  KeyCode.DASH : "-",
  KeyCode.EQUALS : "=",
  KeyCode.TILDE : "`",
};

Map<int, String> SHIFT_MAP = {
  KeyCode.A: "A",
  KeyCode.B: "B",
  KeyCode.C: "C",
  KeyCode.D: "D",
  KeyCode.E: "E",
  KeyCode.F: "F",
  KeyCode.G: "G",
  KeyCode.H: "H",
  KeyCode.I: "I",
  KeyCode.J: "J",
  KeyCode.K: "K",
  KeyCode.L: "L",
  KeyCode.M: "M",
  KeyCode.N: "N",
  KeyCode.O: "O",
  KeyCode.P: "P",
  KeyCode.Q: "Q",
  KeyCode.R: "R",
  KeyCode.S: "S",
  KeyCode.T: "T",
  KeyCode.U: "U",
  KeyCode.V: "V",
  KeyCode.W: "W",
  KeyCode.X: "X",
  KeyCode.Y: "Y",
  KeyCode.Z: "Z",
  KeyCode.ZERO: ")",
  KeyCode.ONE: "!",
  KeyCode.TWO: "@",
  KeyCode.THREE: "#",
  KeyCode.FOUR: "\$",
  KeyCode.FIVE: "%",
  KeyCode.SIX: "^",
  KeyCode.SEVEN: "&",
  KeyCode.EIGHT: "*",
  KeyCode.NINE: "(",
  KeyCode.TILDE : "~",
  KeyCode.COMMA : "<",
  KeyCode.PERIOD : ">",
  KeyCode.SEMICOLON: ":",
  KeyCode.SINGLE_QUOTE : "\"",
  KeyCode.OPEN_SQUARE_BRACKET : "{",
  KeyCode.CLOSE_SQUARE_BRACKET : "}",
  KeyCode.BACKSLASH : "?",
  KeyCode.SLASH : "|",
  KeyCode.DASH : "_",
  KeyCode.EQUALS : "+",
};